# Generated by Django 3.1.7 on 2021-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватар профиля'),
        ),
    ]
