# Generated by Django 3.1.7 on 2021-04-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Чат'),
            preserve_default=False,
        ),
    ]
