# Generated by Django 3.1.7 on 2021-04-22 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210422_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_marks',
            field=models.ManyToManyField(related_name='read_marks', to=settings.AUTH_USER_MODEL, verbose_name='Отметки о прочтении'),
        ),
    ]
