# Generated by Django 3.1.7 on 2021-10-14 19:28

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_read_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('file', models.FileField(upload_to=chat.models.path_to_attachment, verbose_name='Файл')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=chat.models.path_to_attachment_preview, verbose_name='Превью для изображений')),
                ('is_image', models.BooleanField(default=False, verbose_name='Изображение')),
                ('original_name', models.CharField(max_length=50, verbose_name='Оригинальное имя файла')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
